-- Forearm classification and Chinese category naming generated by scripts/classify-forearm-regions.mjs.
ALTER TABLE exercise
    ADD COLUMN forearm_regions JSON NULL AFTER calf_regions;

UPDATE exercise
SET forearm_regions = CAST(CASE source_exercise_id
    WHEN '0994' THEN '["腕伸肌"]'
    WHEN '1016' THEN '["腕屈肌"]'
    WHEN '1411' THEN '["腕伸肌"]'
    WHEN '1412' THEN '["腕屈肌"]'
    WHEN '0079' THEN '["腕伸肌"]'
    WHEN '0082' THEN '["腕伸肌"]'
    WHEN '0104' THEN '["腕屈肌"]'
    WHEN '0126' THEN '["腕屈肌"]'
    WHEN '0125' THEN '["腕屈肌"]'
    WHEN '0210' THEN '["腕伸肌"]'
    WHEN '0224' THEN '["腕屈肌"]'
    WHEN '0247' THEN '["腕屈肌"]'
    WHEN '1437' THEN '["握力"]'
    WHEN '0347' THEN '["旋前旋后"]'
    WHEN '2705' THEN '["旋前旋后"]'
    WHEN '0349' THEN '["旋前旋后"]'
    WHEN '2706' THEN '["旋前旋后"]'
    WHEN '0358' THEN '["腕伸肌"]'
    WHEN '1415' THEN '["腕屈肌"]'
    WHEN '0364' THEN '["腕屈肌"]'
    WHEN '1441' THEN '["腕伸肌"]'
    WHEN '0367' THEN '["腕屈肌"]'
    WHEN '0368' THEN '["腕伸肌"]'
    WHEN '0369' THEN '["腕屈肌"]'
    WHEN '0385' THEN '["腕伸肌"]'
    WHEN '0399' THEN '["旋前旋后"]'
    WHEN '0401' THEN '["腕屈肌"]'
    WHEN '0455' THEN '["握力"]'
    WHEN '0518' THEN '["握力"]'
    WHEN '2288' THEN '["握力"]'
    WHEN '1426' THEN '["腕屈肌"]'
    WHEN '0771' THEN '["腕屈肌"]'
    WHEN '0854' THEN '["握力"]'
    WHEN '1428' THEN '["旋前旋后"]'
    WHEN '0859' THEN '["腕屈肌","腕伸肌"]'
    ELSE NULL
END AS JSON)
WHERE source = 'exercise-dataset'
  AND category_code = 'lower arms';

UPDATE exercise SET category_name = '大臂' WHERE category_code = 'upper arms';
UPDATE exercise SET category_name = '小臂' WHERE category_code = 'lower arms';
