ALTER TABLE exercise
    DROP INDEX uk_exercise_name,
    MODIFY COLUMN name VARCHAR(255) NOT NULL,
    MODIFY COLUMN muscle_group VARCHAR(100) NOT NULL,
    MODIFY COLUMN equipment VARCHAR(100) NOT NULL,
    MODIFY COLUMN instructions TEXT NOT NULL,
    ADD COLUMN source VARCHAR(40) NOT NULL DEFAULT 'manual' AFTER instructions,
    ADD COLUMN source_exercise_id VARCHAR(10) NULL AFTER source,
    ADD COLUMN name_en VARCHAR(255) NULL AFTER source_exercise_id,
    ADD COLUMN category_code VARCHAR(40) NULL AFTER name_en,
    ADD COLUMN category_name VARCHAR(40) NULL AFTER category_code,
    ADD COLUMN category_sort INT NOT NULL DEFAULT 999 AFTER category_name,
    ADD COLUMN equipment_code VARCHAR(80) NULL AFTER category_sort,
    ADD COLUMN muscle_group_code VARCHAR(80) NULL AFTER equipment_code,
    ADD COLUMN target_code VARCHAR(80) NULL AFTER muscle_group_code,
    ADD COLUMN target_name VARCHAR(80) NULL AFTER target_code,
    ADD COLUMN secondary_muscles JSON NULL AFTER target_name,
    ADD COLUMN instructions_en TEXT NULL AFTER secondary_muscles,
    ADD COLUMN image_url VARCHAR(255) NULL AFTER instructions_en,
    ADD COLUMN gif_url VARCHAR(255) NULL AFTER image_url,
    ADD COLUMN attribution VARCHAR(255) NULL AFTER gif_url,
    ADD COLUMN popularity_rank INT NOT NULL DEFAULT 999999 AFTER attribution,
    ADD UNIQUE KEY uk_exercise_source_id (source, source_exercise_id),
    ADD KEY idx_exercise_library_category (category_sort, popularity_rank),
    ADD KEY idx_exercise_library_name (name),
    ADD KEY idx_exercise_library_name_en (name_en);
